services:
  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      # test: [ "CMD", "pg_isready","-h", "db", "-p", "5432"]
      test: [ "CMD", "pg_isready","-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - service-network
      
  server:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 4000:4000
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - service-network

volumes:
  db-data:

networks:
  service-network:
    driver: bridge


