services:
  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      # test: [ "CMD", "pg_isready","-h", "db", "-p", "5432"]
      test: [ "CMD", "pg_isready","-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - service-network

  server:
    build:
      context: .
      target: dev
      args:
        - DATABASE_URL=${DATABASE_URL}
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 4000:4000
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    networks:
      - service-network

volumes:
  db-data:

networks:
  service-network:
    driver: bridge


